# config/default_config/daily.yaml
reportGroup: []
morningTime: "0 10 * * *"
eveningTime: "0 22 * * *"
customTitle: "芙芙心日报"
logoImage: "logo.png"
logoSize: ""
titleFont: "Title.ttf"
titleFontSize: ""
secondaryTitleFont: "Secondary_Title.ttf"
secondaryTitleFontSize: ""
contentFont: "Content.ttf"
contentFontSize: ""
hotModule: "douyin"
apiBase:
  bangumi: "https://api.bgm.tv"
  viki: "https://60s.viki.moe"
theme: "blue"